import { MatchContext, Sentence, Term } from "./depricated/types";
import { Match } from './basicStoreNode';
declare const defaultMatchContext: () => MatchContext;
declare const isTrue: Match;
declare const isFalse: Match;
declare const not: (clause: Match) => Match;
declare const and: (...clauses: Match[]) => Match;
declare const or: (...clauses: Match[]) => Match;
declare const has: (part: Term) => (v: string | RegExp) => Match;
declare const join: (resultName: string) => (prev: Term) => (next: Term) => Match;
declare const objectExists: (sentence: Sentence) => boolean;
declare const joinPrev: (prev: Term) => (next: Term) => Match;
declare const subjectIs: (subject: string | RegExp) => Match;
declare const predicateIs: (predicate: string | RegExp) => Match;
declare const objectIs: (object: string | RegExp) => Match;
export { isTrue, isFalse, not, and, or, has, subjectIs, predicateIs, objectIs, join, joinPrev, objectExists, defaultMatchContext, };
